name: turbo_response
description: A type-safe response wrapper for handling success and failure states with pattern matching and utility methods.
version: 0.2.6
repository: https://github.com/codaveto/turbo_response
issue_tracker: https://github.com/ultrawideturbodev/turbo_response/issues
homepage: https://github.com/ultrawideturbodev/turbo_response

topics:
  - error-handling
  - result
  - response
  - type-safe
  - dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  lints: ^3.0.0
